apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.view.open-cluster-management.io
spec:
  group: view.open-cluster-management.io
  version: v1
  service:
    namespace: open-cluster-management
    name: clusterset-server
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10
  versionPriority: 20
