apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterset-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterset-server
subjects:
  - kind: ServiceAccount
    name: clusterset-server-sa
    namespace: open-cluster-management
